### ISSUE TITLE
Image not found error

### ISSUE THREAD

**Issue by PhoenixRx7** [Nick-Gabe/FAPI-whack-a-potatoe#2]
Probably something super simple I haven't installed or something.
Does the script folder need to be located somewhere specific?
FAP was at the correct resolution, full screen on primary monitor.
Start button was visible.

Traceback (most recent call last):
  File "C:\...\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    return wrappedFunction(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 210, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 405, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 383, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 257, in _locateAll_opencv
    raise ImageNotFoundException('Could not locate the image (highest confidence = %.3f)' % result.max())
pyscreeze.ImageNotFoundException: Could not locate the image (highest confidence = 0.594)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\FAPI-whack-a-potatoe-main\script.py", line 23, in <module>
    location = pyautogui.locateOnScreen(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 174, in wrapper
    raise ImageNotFoundException  # Raise PyAutoGUI's ImageNotFoundException.

**Comment by PhoenixRx7** [comment]
Bueller? Bueller?

**Comment by Nick-Gabe** [comment]
Hey!
Basically the resolution of the game doesn't work if your display resplution is different.
Is your display/notebook at 1920x1080 as well?
